MULTICOLLINEARITY

In [1]:
pip install statsmodels

Collecting statsmodels
  Downloading statsmodels-0.15.0-cp314-cp314-win_amd64.whl.metadata (9.6 kB)
Requirement already satisfied: numpy<3,>=1.23.5 in c:\users\admin\appdata\local\python\pythoncore-3.14-64\lib\site-packages (from statsmodels) (2.5.2)
Requirement already satisfied: scipy!=1.9.2,>=1.8 in c:\users\admin\appdata\local\python\pythoncore-3.14-64\lib\site-packages (from statsmodels) (1.18.1)
Requirement already satisfied: pandas!=2.1.0,>=1.4 in c:\users\admin\appdata\local\python\pythoncore-3.14-64\lib\site-packages (from statsmodels) (3.0.5)
Collecting patsy>=0.5.6 (from statsmodels)
  Downloading patsy-1.0.3-py2.py3-none-any.whl.metadata (3.7 kB)
Requirement already satisfied: packaging>=21.3 in c:\users\admin\appdata\roaming\python\python314\site-packages (from statsmodels) (26.3)
Collecting formulaic>=1.1.0 (from statsmodels)
  Downloading formulaic-1.2.2-py3-none-any.whl.metadata (7.0 kB)
Collecting interface-meta>=1.2.0 (from formulaic>=1.1.0->statsmodels)
  Downloading interface_meta-2.0.1-py3-none-any.whl.metadata (6.4 kB)
Requirement already satisfied: narwhals>=1.17 in c:\users\admin\appdata\local\python\pythoncore-3.14-64\lib\site-packages (from formulaic>=1.1.0->statsmodels) (2.26.0)
Requirement already satisfied: typing-extensions>=4.2.0 in c:\users\admin\appdata\roaming\python\python314\site-packages (from formulaic>=1.1.0->statsmodels) (4.16.0)
Collecting wrapt>=1.17.0rc1 (from formulaic>=1.1.0->statsmodels)
  Downloading wrapt-2.6.0.dev1-cp314-cp314-win_amd64.whl.metadata (7.8 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\admin\appdata\roaming\python\python314\site-packages (from pandas!=2.1.0,>=1.4->statsmodels) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\users\admin\appdata\local\python\pythoncore-3.14-64\lib\site-packages (from pandas!=2.1.0,>=1.4->statsmodels) (2026.4)
Requirement already satisfied: six>=1.5 in c:\users\admin\appdata\roaming\python\python314\site-packages (from python-dateutil>=2.8.2->pandas!=2.1.0,>=1.4->statsmodels) (1.17.0)
Downloading statsmodels-0.15.0-cp314-cp314-win_amd64.whl (11.3 MB)
   ---------------------------------------- 0.0/11.3 MB ? eta -:--:--
   ---------------------------------------- 0.0/11.3 MB ? eta -:--:--
    --------------------------------------- 0.3/11.3 MB ? eta -:--:--
   -- ------------------------------------- 0.8/11.3 MB 1.6 MB/s eta 0:00:07
   --- ------------------------------------ 1.0/11.3 MB 1.7 MB/s eta 0:00:07
   ----- ---------------------------------- 1.6/11.3 MB 1.8 MB/s eta 0:00:06
   ------- -------------------------------- 2.1/11.3 MB 1.9 MB/s eta 0:00:05
   ---------- ----------------------------- 2.9/11.3 MB 2.0 MB/s eta 0:00:05
   ------------ --------------------------- 3.4/11.3 MB 2.1 MB/s eta 0:00:04
   -------------- ------------------------- 4.2/11.3 MB 2.1 MB/s eta 0:00:04
   ---------------- ----------------------- 4.7/11.3 MB 2.0 MB/s eta 0:00:04
   ------------------ --------------------- 5.2/11.3 MB 2.1 MB/s eta 0:00:03
   -------------------- ------------------- 5.8/11.3 MB 2.1 MB/s eta 0:00:03
   ---------------------- ----------------- 6.3/11.3 MB 2.1 MB/s eta 0:00:03
   ------------------------ --------------- 6.8/11.3 MB 2.1 MB/s eta 0:00:03
   ------------------------- -------------- 7.3/11.3 MB 2.1 MB/s eta 0:00:02
   ---------------------------- ----------- 8.1/11.3 MB 2.2 MB/s eta 0:00:02
   ------------------------------ --------- 8.7/11.3 MB 2.2 MB/s eta 0:00:02
   -------------------------------- ------- 9.2/11.3 MB 2.2 MB/s eta 0:00:01
   ---------------------------------- ----- 9.7/11.3 MB 2.2 MB/s eta 0:00:01
   ------------------------------------ --- 10.2/11.3 MB 2.2 MB/s eta 0:00:01
   ------------------------------------ --- 10.5/11.3 MB 2.3 MB/s eta 0:00:01
   -------------------------------------- - 11.0/11.3 MB 2.2 MB/s eta 0:00:01
   ---------------------------------------- 11.3/11.3 MB 2.2 MB/s  0:00:05
Downloading formulaic-1.2.2-py3-none-any.whl (118 kB)
Downloading interface_meta-2.0.1-py3-none-any.whl (15 kB)
Downloading patsy-1.0.3-py2.py3-none-any.whl (233 kB)
Downloading wrapt-2.6.0.dev1-cp314-cp314-win_amd64.whl (106 kB)
Installing collected packages: wrapt, patsy, interface-meta, formulaic, statsmodels

   ---------------------------------------- 0/5 [wrapt]
   ---------------------------------------- 0/5 [wrapt]
   -------- ------------------------------- 1/5 [patsy]
   -------- ------------------------------- 1/5 [patsy]
   -------- ------------------------------- 1/5 [patsy]
   -------- ------------------------------- 1/5 [patsy]
   ---------------- ----------------------- 2/5 [interface-meta]
   ------------------------ --------------- 3/5 [formulaic]
   ------------------------ --------------- 3/5 [formulaic]
   ------------------------ --------------- 3/5 [formulaic]
   ------------------------ --------------- 3/5 [formulaic]
   ------------------------ --------------- 3/5 [formulaic]
   ------------------------ --------------- 3/5 [formulaic]
   ------------------------ --------------- 3/5 [formulaic]
   -------------------------------- ------- 4/5 [statsmodels]
   -------------------------------- ------- 4/5 [statsmodels]
   -------------------------------- ------- 4/5 [statsmodels]
   -------------------------------- ------- 4/5 [statsmodels]
   -------------------------------- ------- 4/5 [statsmodels]
   -------------------------------- ------- 4/5 [statsmodels]
   -------------------------------- ------- 4/5 [statsmodels]
   -------------------------------- ------- 4/5 [statsmodels]
   -------------------------------- ------- 4/5 [statsmodels]
   -------------------------------- ------- 4/5 [statsmodels]
   -------------------------------- ------- 4/5 [statsmodels]
   -------------------------------- ------- 4/5 [statsmodels]
   -------------------------------- ------- 4/5 [statsmodels]
   -------------------------------- ------- 4/5 [statsmodels]
   -------------------------------- ------- 4/5 [statsmodels]
   -------------------------------- ------- 4/5 [statsmodels]
   -------------------------------- ------- 4/5 [statsmodels]
   -------------------------------- ------- 4/5 [statsmodels]
   -------------------------------- ------- 4/5 [statsmodels]
   -------------------------------- ------- 4/5 [statsmodels]
   -------------------------------- ------- 4/5 [statsmodels]
   -------------------------------- ------- 4/5 [statsmodels]
   -------------------------------- ------- 4/5 [statsmodels]
   -------------------------------- ------- 4/5 [statsmodels]
   -------------------------------- ------- 4/5 [statsmodels]
   -------------------------------- ------- 4/5 [statsmodels]
   -------------------------------- ------- 4/5 [statsmodels]
   -------------------------------- ------- 4/5 [statsmodels]
   -------------------------------- ------- 4/5 [statsmodels]
   -------------------------------- ------- 4/5 [statsmodels]
   -------------------------------- ------- 4/5 [statsmodels]
   -------------------------------- ------- 4/5 [statsmodels]
   -------------------------------- ------- 4/5 [statsmodels]
   -------------------------------- ------- 4/5 [statsmodels]
   -------------------------------- ------- 4/5 [statsmodels]
   -------------------------------- ------- 4/5 [statsmodels]
   -------------------------------- ------- 4/5 [statsmodels]
   -------------------------------- ------- 4/5 [statsmodels]
   -------------------------------- ------- 4/5 [statsmodels]
   -------------------------------- ------- 4/5 [statsmodels]
   -------------------------------- ------- 4/5 [statsmodels]
   -------------------------------- ------- 4/5 [statsmodels]
   -------------------------------- ------- 4/5 [statsmodels]
   -------------------------------- ------- 4/5 [statsmodels]
   -------------------------------- ------- 4/5 [statsmodels]
   -------------------------------- ------- 4/5 [statsmodels]
   -------------------------------- ------- 4/5 [statsmodels]
   -------------------------------- ------- 4/5 [statsmodels]
   -------------------------------- ------- 4/5 [statsmodels]
   -------------------------------- ------- 4/5 [statsmodels]
   -------------------------------- ------- 4/5 [statsmodels]
   -------------------------------- ------- 4/5 [statsmodels]
   -------------------------------- ------- 4/5 [statsmodels]
   -------------------------------- ------- 4/5 [statsmodels]
   -------------------------------- ------- 4/5 [statsmodels]
   -------------------------------- ------- 4/5 [statsmodels]
   -------------------------------- ------- 4/5 [statsmodels]
   -------------------------------- ------- 4/5 [statsmodels]
   -------------------------------- ------- 4/5 [statsmodels]
   -------------------------------- ------- 4/5 [statsmodels]
   -------------------------------- ------- 4/5 [statsmodels]
   -------------------------------- ------- 4/5 [statsmodels]
   -------------------------------- ------- 4/5 [statsmodels]
   -------------------------------- ------- 4/5 [statsmodels]
   -------------------------------- ------- 4/5 [statsmodels]
   -------------------------------- ------- 4/5 [statsmodels]
   -------------------------------- ------- 4/5 [statsmodels]
   -------------------------------- ------- 4/5 [statsmodels]
   -------------------------------- ------- 4/5 [statsmodels]
   -------------------------------- ------- 4/5 [statsmodels]
   -------------------------------- ------- 4/5 [statsmodels]
   -------------------------------- ------- 4/5 [statsmodels]
   -------------------------------- ------- 4/5 [statsmodels]
   -------------------------------- ------- 4/5 [statsmodels]
   -------------------------------- ------- 4/5 [statsmodels]
   -------------------------------- ------- 4/5 [statsmodels]
   -------------------------------- ------- 4/5 [statsmodels]
   -------------------------------- ------- 4/5 [statsmodels]
   -------------------------------- ------- 4/5 [statsmodels]
   -------------------------------- ------- 4/5 [statsmodels]
   -------------------------------- ------- 4/5 [statsmodels]
   -------------------------------- ------- 4/5 [statsmodels]
   -------------------------------- ------- 4/5 [statsmodels]
   -------------------------------- ------- 4/5 [statsmodels]
   -------------------------------- ------- 4/5 [statsmodels]
   -------------------------------- ------- 4/5 [statsmodels]
   -------------------------------- ------- 4/5 [statsmodels]
   -------------------------------- ------- 4/5 [statsmodels]
   -------------------------------- ------- 4/5 [statsmodels]
   -------------------------------- ------- 4/5 [statsmodels]
   -------------------------------- ------- 4/5 [statsmodels]
   -------------------------------- ------- 4/5 [statsmodels]
   -------------------------------- ------- 4/5 [statsmodels]
   -------------------------------- ------- 4/5 [statsmodels]
   -------------------------------- ------- 4/5 [statsmodels]
   -------------------------------- ------- 4/5 [statsmodels]
   -------------------------------- ------- 4/5 [statsmodels]
   -------------------------------- ------- 4/5 [statsmodels]
   -------------------------------- ------- 4/5 [statsmodels]
   -------------------------------- ------- 4/5 [statsmodels]
   -------------------------------- ------- 4/5 [statsmodels]
   -------------------------------- ------- 4/5 [statsmodels]
   -------------------------------- ------- 4/5 [statsmodels]
   -------------------------------- ------- 4/5 [statsmodels]
   -------------------------------- ------- 4/5 [statsmodels]
   -------------------------------- ------- 4/5 [statsmodels]
   -------------------------------- ------- 4/5 [statsmodels]
   -------------------------------- ------- 4/5 [statsmodels]
   -------------------------------- ------- 4/5 [statsmodels]
   -------------------------------- ------- 4/5 [statsmodels]
   -------------------------------- ------- 4/5 [statsmodels]
   -------------------------------- ------- 4/5 [statsmodels]
   -------------------------------- ------- 4/5 [statsmodels]
   -------------------------------- ------- 4/5 [statsmodels]
   -------------------------------- ------- 4/5 [statsmodels]
   -------------------------------- ------- 4/5 [statsmodels]
   -------------------------------- ------- 4/5 [statsmodels]
   -------------------------------- ------- 4/5 [statsmodels]
   -------------------------------- ------- 4/5 [statsmodels]
   -------------------------------- ------- 4/5 [statsmodels]
   -------------------------------- ------- 4/5 [statsmodels]
   -------------------------------- ------- 4/5 [statsmodels]
   -------------------------------- ------- 4/5 [statsmodels]
   -------------------------------- ------- 4/5 [statsmodels]
   -------------------------------- ------- 4/5 [statsmodels]
   ---------------------------------------- 5/5 [statsmodels]

Successfully installed formulaic-1.2.2 interface-meta-2.0.1 patsy-1.0.3 statsmodels-0.15.0 wrapt-2.6.0.dev1
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.3 -> 26.2.2
[notice] To update, run: C:\Users\Admin\AppData\Local\Python\pythoncore-3.14-64\python.exe -m pip install --upgrade pip

In [4]:
import pandas as pd
import numpy as np

from statsmodels.stats.outliers_influence import (variance_inflation_factor)

df = pd.DataFrame({
    "Area_sqft": [
        1000, 1500, 2000, 2500, 3000, 3500
    ],
    "Area_sqm": [
        92.9, 139.4, 185.8, 232.3, 278.7, 325.2
    ],
    "Bedrooms": [2, 3, 3, 4, 4, 5],
    "Age": [15, 10, 8, 5, 3, 2]
})

In [6]:
X = df.copy()

vif_data = pd.DataFrame()
vif_data["Feature"] = X.columns

vif_data["VIF"] = [
    variance_inflation_factor(
        X.values, i
    )
    for i in range(X.shape[1])
]

print("\nVIF Results:")
vif_data.round(2)

C:\Users\Admin\AppData\Local\Temp\ipykernel_11660\3180647036.py:7: UserWarning: The design matrix is poorly conditioned (condition number=4.21e+15). VIF calculations may be numerically unstable.
  variance_inflation_factor(
C:\Users\Admin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\statsmodels\stats\outliers_influence.py:235: SingularMatrixWarning: The design matrix is rank-deficient. The model parameters are not uniquely determined.
  r_sq = OLS(x_i, x_noti).fit().rsquared

VIF Results:

     Feature           VIF
0  Area_sqft  1.000800e+15
1   Area_sqm  1.000800e+15
2   Bedrooms  1.000800e+15
3        Age  2.228000e+01

In [12]:
df = pd.DataFrame({
    #"Area_sqft": [1000, 1500, 2000, 2500, 3000, 3500 ]
    #"Area_sqm": [92.9, 139.4, 185.8, 232.3, 278.7, 325.2]
    "Bedrooms": [2, 3, 3, 4, 4, 5],
    "Age": [15, 10, 8, 5, 3, 2]
})

X = df.copy()

vif_data = pd.DataFrame()
vif_data["Feature"] = X.columns

vif_data["VIF"] = [
    variance_inflation_factor(
        X.values, i
    )
    for i in range(X.shape[1])
]

print("\nVIF Results:")
vif_data.round(2)

VIF Results:

    Feature    VIF
0  Bedrooms  12.25
1       Age  12.25

In [19]:
df = pd.DataFrame({
    #"Area_sqft": [1000, 1500, 2000, 2500, 3000, 3500 ]
    "Area_sqm": [92.9, 139.4, 185.8, 232.3, 278.7, 325.2],
    "Bedrooms": [2, 3, 3, 4, 4, 5],
    "Age": [15, 10, 8, 5, 3, 2]
})

X = df.copy()

vif_data = pd.DataFrame()
vif_data["Feature"] = X.columns

vif_data["VIF"] = [
    variance_inflation_factor(
        X.values, i
    )
    for i in range(X.shape[1])
]

print("\nVIF Results:")
vif_data.round(2)

VIF Results:

    Feature    VIF
0  Area_sqm  29.23
1  Bedrooms  17.10
2       Age  22.28

In [20]:
df = pd.DataFrame({
    "Area_sqft": [1000, 1500, 2000, 2500, 3000, 3500 ],
    "Area_sqm": [92.9, 139.4, 185.8, 232.3, 278.7, 325.2],
    #"Bedrooms": [2, 3, 3, 4, 4, 5],
    #"Age": [15, 10, 8, 5, 3, 2]
})

X = df.copy()

vif_data = pd.DataFrame()
vif_data["Feature"] = X.columns

vif_data["VIF"] = [
    variance_inflation_factor(
        X.values, i
    )
    for i in range(X.shape[1])
]

print("\nVIF Results:")
vif_data.round(2)

VIF Results:

     Feature          VIF
0  Area_sqft  11014796.04
1   Area_sqm  11014796.04

ols method

In [22]:
import pandas as pd
import numpy as np

In [28]:
df = pd.DataFrame({
    "Area_sqft": [
        1000, 1500, 2000, 2500, 3000, 3500
    ],
    "floor": [2,3,2,4,3,2],
    "Bedrooms": [2, 3, 3, 4, 4, 5],
    "Age": [15, 10, 8, 5, 3, 2],
    "price": [120000,130000,140000,150000,160000,170000]
})

In [29]:
import statsmodels.api as sm

In [30]:
df

   Area_sqft  floor  Bedrooms  Age   price
0       1000      2         2   15  120000
1       1500      3         3   10  130000
2       2000      2         3    8  140000
3       2500      4         4    5  150000
4       3000      3         4    3  160000
5       3500      2         5    2  170000

In [31]:
x= df.iloc[:,:-1]
y= df.iloc[:,-1]

In [32]:
x

   Area_sqft  floor  Bedrooms  Age
0       1000      2         2   15
1       1500      3         3   10
2       2000      2         3    8
3       2500      4         4    5
4       3000      3         4    3
5       3500      2         5    2

In [33]:
y

0    120000
1    130000
2    140000
3    150000
4    160000
5    170000
Name: price, dtype: int64

In [35]:
x=sm.add_constant(x)

In [37]:
model = sm.OLS(y,x).fit()
print(model.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:                  price   R-squared:                       1.000
Model:                            OLS   Adj. R-squared:                  1.000
Method:                 Least Squares   F-statistic:                 6.517e+27
Date:                Sun, 01 Nov 2026   Prob (F-statistic):           9.29e-15
Time:                        12:57:41   Log-Likelihood:                 129.30
No. Observations:                   6   AIC:                            -248.6
Df Residuals:                       1   BIC:                            -249.7
Df Model:                           4
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const           1e+05   3.33e-09      3e+13      0.000       1e+05       1e+05
Area_sqft     20.0000      1e-12   1.99e+13      0.000      20.000      20.000
floor       -1.91e-11   2.24e-10     -0.085      0.946   -2.87e-09    2.83e-09
Bedrooms    -2.91e-11   4.93e-10     -0.059      0.962    -6.3e-09    6.24e-09
Age        -7.276e-12   1.59e-10     -0.046      0.971   -2.02e-09    2.01e-09
==============================================================================
Omnibus:                          nan   Durbin-Watson:                   0.259
Prob(Omnibus):                    nan   Jarque-Bera (JB):                0.498
Skew:                          -0.056   Prob(JB):                        0.780
Kurtosis:                       1.594   Cond. No.                     7.59e+04
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 7.59e+04. This might indicate that there are
strong multicollinearity or other numerical problems.

C:\Users\Admin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\statsmodels\regression\linear_model.py:3158: ValueWarning: omni_normtest is not valid with less than 8 observations; 6 samples were given.
  omni, omnipv = cached("omni_normtest", lambda: omni_normtest(self.wresid))

In [38]:
df = pd.DataFrame({
    "Area_sqft": [
        1000, 1500, 2000, 2500, 3000, 3500
    ],
    #"floor": [2,3,2,4,3,2],
    "Bedrooms": [2, 3, 3, 4, 4, 5],
    "Age": [15, 10, 8, 5, 3, 2],
    "price": [120000,130000,140000,150000,160000,170000]
})

In [39]:
model = sm.OLS(y,x).fit()
print(model.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:                  price   R-squared:                       1.000
Model:                            OLS   Adj. R-squared:                  1.000
Method:                 Least Squares   F-statistic:                 6.517e+27
Date:                Sun, 01 Nov 2026   Prob (F-statistic):           9.29e-15
Time:                        13:03:28   Log-Likelihood:                 129.30
No. Observations:                   6   AIC:                            -248.6
Df Residuals:                       1   BIC:                            -249.7
Df Model:                           4
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const           1e+05   3.33e-09      3e+13      0.000       1e+05       1e+05
Area_sqft     20.0000      1e-12   1.99e+13      0.000      20.000      20.000
floor       -1.91e-11   2.24e-10     -0.085      0.946   -2.87e-09    2.83e-09
Bedrooms    -2.91e-11   4.93e-10     -0.059      0.962    -6.3e-09    6.24e-09
Age        -7.276e-12   1.59e-10     -0.046      0.971   -2.02e-09    2.01e-09
==============================================================================
Omnibus:                          nan   Durbin-Watson:                   0.259
Prob(Omnibus):                    nan   Jarque-Bera (JB):                0.498
Skew:                          -0.056   Prob(JB):                        0.780
Kurtosis:                       1.594   Cond. No.                     7.59e+04
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 7.59e+04. This might indicate that there are
strong multicollinearity or other numerical problems.

C:\Users\Admin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\statsmodels\regression\linear_model.py:3158: ValueWarning: omni_normtest is not valid with less than 8 observations; 6 samples were given.
  omni, omnipv = cached("omni_normtest", lambda: omni_normtest(self.wresid))